settings:
  username: "rahatbd"
  commit_msg: "âš¡ Update recent-activity"
  max_lines: 5
  readme_file: "./README.md"
  url_text: "{REPO}{ID}"
  date:
    timezone: "America/Toronto"
    text: "Last Updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_username: "readme-bot"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
messages:
  comments: "ğŸ’¬ Commented on {ID} in {REPO}"
  issue_opened: "âš ï¸ Opened issue {ID} in {REPO}"
  issue_closed: "â¤¬ Closed issue {ID} in {REPO}"
  pr_opened: "âŒ— Opened PR {ID} in {REPO}"
  pr_closed: "â¤« Closed PR {ID} in {REPO}"
  pr_merged: "ğŸ‰ Merged PR {ID} in {REPO}"
  create_repo: "ğŸŒ¹ Created new repository {REPO}"
  fork_repo: "ğŸ”± Forked {FORK} from {REPO}"
  wiki_create: "ğŸ“– Created new wiki page {WIKI} in {REPO}"
  added_member: "ğŸ¤ Became collaborator on {REPO}"
  changes_approved: "â˜‘ï¸ Approved {ID} in {REPO}"
  changes_requested: "â“ Requested {AMOUNT} change(s) in {ID} in {REPO}"
  new_release: "âœŒï¸ Released {ID} in {REPO}"
  new_star: "â­ Starred {REPO}"
